### ISSUE TITLE
'Rune' system

### ISSUE THREAD

**Issue by bdmax1040** [bdmax1040/EquinoxCore-1.18.2#8]
Introduction of the **Rune** system. This is a set of 5 custom in-game runes which act as custom items. Upon collection of these, you can craft them into a tablet and redeem that for extra time within the world.

Red - "Odin"
Orange - "Dragaz"
Lime Green - "Lagu"
Light Blue - "Sigel"
Purple - "Kaun"

Each tablet can be redeemed to give you an extra 30 minutes, or, you can craft all 5 up into the "Stargate Tablet" which grants you either 5 or 10 extra hours of playtime. Each custom achievement that a players completes, they get a rune, and this is where the encouragement to do the tasks gives you a reward, and this this case, it is extra playtime. Some will be easier, and some will be harder, earning a specific type of gain. 

Once a player dies, we could make them drop a rune as well which means that there's a chance to live on longer after one player has died.

Adding other custom items could be cool to control things other than time, but I'm not 100% sure yet!

References for all of the Runes can be found here - https://sonsofvikings.com/blogs/history/viking-runes-guide-runic-alphabet-meanings-nordic-celtic-letters

**Comment by JackTheWilliams** [comment]
odin

**Comment by bdmax1040** [comment]
All runes have now been added, I just need to add the relevant functions and do the maths side to calculate taking the time off of the players counter
